name: to_do_list
description: A new Flutter project.
ublish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

## Slidy Scripts 
vars: 
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts: 
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animate_do: ^2.1.0
  animate_icons: ^2.0.0
  animations: ^2.0.2
  dartz: ^0.10.1
  dropdown_search: ^2.0.1 
  flash: ^2.0.3+2
  flutter_mobx: ^2.0.4
  flutter_modular: ^4.5.0
  flutter_slidable: ^1.2.0
  flutter_staggered_animations: ^1.0.0 
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  hive: ^2.0.6
  mobx: ^2.0.6+1
  path_provider: ^2.0.9 

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8

  
flutter:
  uses-material-design: true

  assets:
    - assets/avatar.png
    - assets/images/